set(SCRUTINY_SOURCES 
	src/scrutiny_main_handler.cpp
	src/scrutiny_loop_handler.cpp
	src/protocol/scrutiny_comm_handler.cpp
	src/scrutiny_crc.cpp
	src/scrutiny_software_id.cpp

	inc/scrutiny.h
	inc/scrutiny_config.h
	inc/scrutiny_crc.h
	inc/scrutiny_loop_handler.h
	inc/scrutiny_main_handler.h
	inc/scrutiny_setup.h
	inc/scrutiny_software_id.h
	inc/scrutiny_timebase.h
	inc/protocol/scrutiny_protocol.h
	inc/protocol/scrutiny_comm_handler.h
	inc/protocol/scrutiny_protocol_definitions.h
	)